"""Add unique constraint for field names in sheet

Revision ID: 1ab5e4c66cfa
Revises: e6bbe662a6ef
Create Date: 2025-10-12 15:00:37.798981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab5e4c66cfa'
down_revision = 'e6bbe662a6ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_definition', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_sheet_field_name', ['sheet_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_definition', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sheet_field_name', type_='unique')

    # ### end Alembic commands ###
