"""Add display/actual value support for choices and export options

Revision ID: 3f93fa62401d
Revises: fe5c3380c5de
Create Date: 2025-10-16 09:35:03.998179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f93fa62401d'
down_revision = 'fe5c3380c5de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_definition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('export_word_as_label', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('export_excel_as_label', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.alter_column('options',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_definition', schema=None) as batch_op:
        batch_op.alter_column('options',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('export_excel_as_label')
        batch_op.drop_column('export_word_as_label')

    # ### end Alembic commands ###
