"""Add word_template_path to Template model

Revision ID: 4f12fb611061
Revises: 1ab5e4c66cfa
Create Date: 2025-10-14 14:00:32.608113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f12fb611061'
down_revision = '1ab5e4c66cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word_template_path', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.drop_column('word_template_path')

    # ### end Alembic commands ###
