"""Initial migration

Revision ID: aa019ceb8626
Revises:
Create Date: 2025-10-16 11:28:35.498711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa019ceb8626'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=False),
    sa.Column('procurement_method', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biz_review_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('seq_num', sa.String(length=50), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=True),
    sa.Column('criteria', sa.Text(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('min_score', sa.Float(), nullable=True),
    sa.Column('step', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deduct_review_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('seq_num', sa.String(length=50), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=True),
    sa.Column('criteria', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('effective_supplier_principle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('seq_num', sa.String(length=50), nullable=True),
    sa.Column('effective_supplier_count', sa.String(length=200), nullable=True),
    sa.Column('candidate_count', sa.String(length=200), nullable=True),
    sa.Column('winner_count', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixed_form_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=100), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('key_tech_indicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('seq_num', sa.String(length=50), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('tech_spec', sa.Text(), nullable=True),
    sa.Column('requirement', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multi_share_allocation_principle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('seq_num', sa.String(length=50), nullable=True),
    sa.Column('winner_count', sa.String(length=100), nullable=True),
    sa.Column('rank_1', sa.String(length=50), nullable=True),
    sa.Column('rank_2', sa.String(length=50), nullable=True),
    sa.Column('rank_3', sa.String(length=50), nullable=True),
    sa.Column('rank_4', sa.String(length=50), nullable=True),
    sa.Column('rank_5', sa.String(length=50), nullable=True),
    sa.Column('rank_6', sa.String(length=50), nullable=True),
    sa.Column('rank_7', sa.String(length=50), nullable=True),
    sa.Column('rank_8', sa.String(length=50), nullable=True),
    sa.Column('rank_9', sa.String(length=50), nullable=True),
    sa.Column('rank_10', sa.String(length=50), nullable=True),
    sa.Column('rank_11', sa.String(length=50), nullable=True),
    sa.Column('rank_12', sa.String(length=50), nullable=True),
    sa.Column('rank_13', sa.String(length=50), nullable=True),
    sa.Column('rank_14', sa.String(length=50), nullable=True),
    sa.Column('rank_15', sa.String(length=50), nullable=True),
    sa.Column('rank_16', sa.String(length=50), nullable=True),
    sa.Column('rank_17', sa.String(length=50), nullable=True),
    sa.Column('rank_18', sa.String(length=50), nullable=True),
    sa.Column('rank_19', sa.String(length=50), nullable=True),
    sa.Column('rank_20', sa.String(length=50), nullable=True),
    sa.Column('rank_21', sa.String(length=50), nullable=True),
    sa.Column('rank_22', sa.String(length=50), nullable=True),
    sa.Column('rank_23', sa.String(length=50), nullable=True),
    sa.Column('rank_24', sa.String(length=50), nullable=True),
    sa.Column('rank_25', sa.String(length=50), nullable=True),
    sa.Column('rank_26', sa.String(length=50), nullable=True),
    sa.Column('rank_27', sa.String(length=50), nullable=True),
    sa.Column('rank_28', sa.String(length=50), nullable=True),
    sa.Column('rank_29', sa.String(length=50), nullable=True),
    sa.Column('rank_30', sa.String(length=50), nullable=True),
    sa.Column('rank_31', sa.String(length=50), nullable=True),
    sa.Column('rank_32', sa.String(length=50), nullable=True),
    sa.Column('rank_33', sa.String(length=50), nullable=True),
    sa.Column('rank_34', sa.String(length=50), nullable=True),
    sa.Column('rank_35', sa.String(length=50), nullable=True),
    sa.Column('rank_36', sa.String(length=50), nullable=True),
    sa.Column('rank_37', sa.String(length=50), nullable=True),
    sa.Column('rank_38', sa.String(length=50), nullable=True),
    sa.Column('rank_39', sa.String(length=50), nullable=True),
    sa.Column('rank_40', sa.String(length=50), nullable=True),
    sa.Column('rank_41', sa.String(length=50), nullable=True),
    sa.Column('rank_42', sa.String(length=50), nullable=True),
    sa.Column('rank_43', sa.String(length=50), nullable=True),
    sa.Column('rank_44', sa.String(length=50), nullable=True),
    sa.Column('rank_45', sa.String(length=50), nullable=True),
    sa.Column('rank_46', sa.String(length=50), nullable=True),
    sa.Column('rank_47', sa.String(length=50), nullable=True),
    sa.Column('rank_48', sa.String(length=50), nullable=True),
    sa.Column('rank_49', sa.String(length=50), nullable=True),
    sa.Column('rank_50', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_review_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('seq_num', sa.String(length=50), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=True),
    sa.Column('criteria', sa.Text(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('min_score', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_review_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('seq_num', sa.String(length=50), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=True),
    sa.Column('criteria', sa.Text(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('min_score', sa.Float(), nullable=True),
    sa.Column('step', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share_allocation_principle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('seq_num', sa.String(length=50), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('ratio', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tech_review_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('seq_num', sa.String(length=50), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=True),
    sa.Column('criteria', sa.Text(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('min_score', sa.Float(), nullable=True),
    sa.Column('step', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_template_chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheet_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sheet_type', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('model_identifier', sa.String(length=100), nullable=True),
    sa.Column('word_template_chapter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_template_chapter_id'], ['word_template_chapter.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_template_chapter_id')
    )
    op.create_table('conditional_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet_definition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('default_value', sa.String(length=255), nullable=True),
    sa.Column('help_tip', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet_definition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sheet_id', 'name', name='uq_sheet_field_name')
    )
    op.create_table('validation_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('rule_value', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['field_definition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_rule')
    op.drop_table('field_definition')
    op.drop_table('conditional_rule')
    op.drop_table('sheet_definition')
    op.drop_table('word_template_chapter')
    op.drop_table('tech_review_item')
    op.drop_table('share_allocation_principle')
    op.drop_table('service_review_item')
    op.drop_table('section')
    op.drop_table('price_review_item')
    op.drop_table('multi_share_allocation_principle')
    op.drop_table('key_tech_indicator')
    op.drop_table('fixed_form_data')
    op.drop_table('effective_supplier_principle')
    op.drop_table('deduct_review_item')
    op.drop_table('biz_review_item')
    op.drop_table('template')
    op.drop_table('project')
    # ### end Alembic commands ###
