"""Add export format flags to FieldDefinition

Revision ID: ce0c73563059
Revises: aa019ceb8626
Create Date: 2025-10-16 11:29:28.034607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0c73563059'
down_revision = 'aa019ceb8626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_definition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('export_word_as_label', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('export_excel_as_label', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_definition', schema=None) as batch_op:
        batch_op.drop_column('export_excel_as_label')
        batch_op.drop_column('export_word_as_label')

    # ### end Alembic commands ###
